name = "cloudflare-ai-chat"
main = "src/worker.ts"
compatibility_date = "2024-09-30"

[site]
bucket = "./public"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]

[ai]
binding = "AI"


